openapi: 3.0.0
info:
  title: Cart API
  version: 1.0.0
paths:
  /:
    post:
      tags:
        - Cart
      summary: Create a new cart
      operationId: createCartController
      responses:
        '200':
          description: Cart created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        '400':
          description: Cart could not be created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /{cid}:
    get:
      tags:
        - Cart
      summary: Get a cart by ID
      operationId: getCartByIdController
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        '404':
          description: Cart ID not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - Cart
      summary: Clear a cart by ID
      operationId: clearCartController
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cart deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessMessage"
        '404':
          description: Cart ID not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /{cid}/products/{pid}:
    post:
      tags:
        - Cart
      summary: Add a product to a cart by ID
      operationId: addProductToCartByIdController
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
      responses:
        '200':
          description: Product added to cart successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        '400':
          description: Product could not be added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - Cart
      summary: Delete a product in a cart by ID
      operationId: deleteProductInCartByIdController
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product deleted from cart successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        '400':
          description: Error deleting product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


  /add-to-cart:
    post:
      tags:
        - Cart
      summary: User adds product to cart
      operationId: userAddToCartController
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                prodId:
                  type: string
                quantity:
                  type: integer
      responses:
        '200':
          description: Product added to cart successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        '400':
          description: Error adding product to cart
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
        products:
          type: array
          items:
            type: object
            properties:
              product:
                $ref: '#/components/schemas/Product'
              quantity:
                type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    